// <auto-generated />
using System;
using BEZAO_PayDAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BEZAO_PayDAL.Migrations
{
    [DbContext(typeof(BezaoPayContext))]
    [Migration("20210826081323_somethingnice12")]
    partial class somethingnice12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BEZAO_PayDAL.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(38,2)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = 760015555,
                            Balance = 23456782340m
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = 222833403,
                            Balance = 56000000000m
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = 456723646,
                            Balance = 78345678230m
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = 1642347213,
                            Balance = 63723456780m
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = 753485382,
                            Balance = 88978234000m
                        });
                });

            modelBuilder.Entity("BEZAO_PayDAL.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(38,2)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionMode")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50000000m,
                            TimeStamp = new DateTime(2021, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionMode = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 60000000m,
                            TimeStamp = new DateTime(2022, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionMode = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 70000000m,
                            TimeStamp = new DateTime(2023, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionMode = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 80000000m,
                            TimeStamp = new DateTime(2024, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionMode = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 90000000m,
                            TimeStamp = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionMode = 1,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("BEZAO_PayDAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Birthday = new DateTime(1990, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 8, 26, 9, 13, 22, 250, DateTimeKind.Local).AddTicks(7056),
                            Email = "sorry.sir@abeg.com",
                            IsActive = true,
                            Name = "Francis Sorry"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Birthday = new DateTime(1420, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 8, 26, 9, 13, 22, 252, DateTimeKind.Local).AddTicks(8646),
                            Email = "badguy@BBA.com",
                            IsActive = true,
                            Name = "GrandMaster KC"
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            Birthday = new DateTime(1420, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 8, 26, 9, 13, 22, 252, DateTimeKind.Local).AddTicks(8733),
                            Email = "dara.sage@ned.com",
                            IsActive = true,
                            Name = "Dara John"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            Birthday = new DateTime(1420, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 8, 26, 9, 13, 22, 252, DateTimeKind.Local).AddTicks(8740),
                            Email = "sadboy@BBA.com",
                            IsActive = true,
                            Name = "Kachi !Thename"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            Birthday = new DateTime(1420, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 8, 26, 9, 13, 22, 252, DateTimeKind.Local).AddTicks(8744),
                            Email = "omo@BBA.com",
                            IsActive = true,
                            Name = "Sammy ROCBAFDEZ"
                        });
                });

            modelBuilder.Entity("BEZAO_PayDAL.Entities.Transaction", b =>
                {
                    b.HasOne("BEZAO_PayDAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BEZAO_PayDAL.Entities.User", b =>
                {
                    b.HasOne("BEZAO_PayDAL.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
