// <auto-generated />
using System;
using BEZAO_PayDAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BEZAO_PayDAL.Migrations
{
    [DbContext(typeof(BezaoPayContext))]
    [Migration("20210828120211_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BEZAO_PayDAL.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(38,2)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = 760015555,
                            Balance = 23456782340m
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = 222833403,
                            Balance = 56000000000m
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = 456723646,
                            Balance = 78345678230m
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = 1642347213,
                            Balance = 63723456780m
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = 753485382,
                            Balance = 88978234000m
                        });
                });

            modelBuilder.Entity("BEZAO_PayDAL.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(38,2)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionMode")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50000000m,
                            TimeStamp = new DateTime(2021, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionMode = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 60000000m,
                            TimeStamp = new DateTime(2022, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionMode = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 70000000m,
                            TimeStamp = new DateTime(2023, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionMode = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 80000000m,
                            TimeStamp = new DateTime(2024, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionMode = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 90000000m,
                            TimeStamp = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionMode = 1,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("BEZAO_PayDAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Birthday = new DateTime(1990, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 8, 28, 13, 2, 10, 817, DateTimeKind.Local).AddTicks(3056),
                            Email = "sorry.sir@abeg.com",
                            IsActive = true,
                            Name = "Francis Sorry",
                            Password = "EHExEnk2/IeRznXvYwczgjNVEnK+9a6cHwn4srEg",
                            Salt = "31-d2-89-94-04-ec-50-b5-b6-3e-85-57-46-d5-0e-d4",
                            Username = "francissorry"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Birthday = new DateTime(1420, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 8, 28, 13, 2, 10, 850, DateTimeKind.Local).AddTicks(945),
                            Email = "badguy@BBA.com",
                            IsActive = true,
                            Name = "GrandMaster KC",
                            Password = "Mu0qwsdQiVHMmf2Q+bgfpHDN7LaJJWx9Li5j/MYZ",
                            Salt = "c0-a6-b8-32-09-3b-36-87-30-8c-db-73-24-8e-d5-a0",
                            Username = "grandmasterkc"
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            Birthday = new DateTime(1420, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 8, 28, 13, 2, 10, 869, DateTimeKind.Local).AddTicks(5922),
                            Email = "dara.sage@ned.com",
                            IsActive = true,
                            Name = "Dara John",
                            Password = "SPXFL8vB9Yq+6IJ6xkQQEcvLyqd7VN1Y3oPkePz3",
                            Salt = "a1-d6-27-bc-20-2e-77-b0-6a-e0-92-1f-7d-5e-72-1a",
                            Username = "darajohn"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            Birthday = new DateTime(1420, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 8, 28, 13, 2, 10, 892, DateTimeKind.Local).AddTicks(2621),
                            Email = "sadboy@BBA.com",
                            IsActive = true,
                            Name = "Kachi !Thename",
                            Password = "kFtGywq+kw2cppcVaNLucER4FHsuhaQDKepy4y5t",
                            Salt = "8a-20-ba-56-99-1d-a7-0f-9f-b2-06-31-44-fb-8a-12",
                            Username = "kachi!thename"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            Birthday = new DateTime(1420, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 8, 28, 13, 2, 10, 908, DateTimeKind.Local).AddTicks(6282),
                            Email = "omo@BBA.com",
                            IsActive = true,
                            Name = "Sammy ROCBAFDEZ",
                            Password = "46KmE/G8cypjnEA59P3bmX5aAy6xvw+H9a/7NLdw",
                            Salt = "c7-c8-9d-af-01-50-fa-b0-f2-e8-83-3e-ee-9f-e5-ba",
                            Username = "sammyrocbafdez"
                        });
                });

            modelBuilder.Entity("BEZAO_PayDAL.Entities.Transaction", b =>
                {
                    b.HasOne("BEZAO_PayDAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BEZAO_PayDAL.Entities.User", b =>
                {
                    b.HasOne("BEZAO_PayDAL.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
